// Shared test helpers (no tests of its own). It is named *.test.ts so the build
// config leaves it out of dist/ and tsconfig.test.json type-checks it with
// Node's types.

import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { randomBytes } from 'node:crypto';
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseArgs } from 'node:util';
import type { Io, ParseArgs } from './io.ts';
import { SEED_VARIABLE } from './seed.ts';

export { SEED_VARIABLE };

/** The built bin: the child-process tests drive what npm publishes. */
export const BIN = fileURLToPath(new URL('../dist/bin/main.js', import.meta.url));

export const GOLDEN_PATH = fileURLToPath(new URL('../../produce-core/src/__fixtures__/reference-golden.json', import.meta.url));

export interface GoldenCase {
  name: string;
  input: Record<string, unknown>;
  expected: { serializedJson: string; contentHashSha256: string | null; envelopeHash?: string; nodeId?: string };
}

export const golden = JSON.parse(readFileSync(GOLDEN_PATH, 'utf8')) as {
  envelopeCases: GoldenCase[];
  attestationCases: GoldenCase[];
};

// RFC 8032 §7.1 TEST 1, the published test vector's 32-byte seed (hex): public, so
// what it signs can be regenerated byte for byte by anyone.
export const RFC8032_TEST_1 = '9d61b19deffd5a60ba844af492ec2cc44449c5697b326919703bac031cae7f60';
export const RFC8032_TEST_1_B64 = Buffer.from(RFC8032_TEST_1, 'hex').toString('base64');

/** A fresh Ed25519 seed for one test, as bytes and as the variable's value. Never a real key. */
export function newSeed(): { bytes: Buffer; b64: string } {
  const bytes = randomBytes(32);
  return { bytes, b64: bytes.toString('base64') };
}

export interface CliResult {
  code: number | null;
  stdout: Buffer;
  stderr: Buffer;
  out: string;
  err: string;
  json(): Record<string, unknown>;
}

/**
 * Run the built CLI in a child process with exactly the environment given: no
 * variable leaks in from the test runner's own environment.
 */
export function cli(args: string[], options: { env?: Record<string, string>; stdin?: string } = {}): CliResult {
  assert.ok(existsSync(BIN), `${BIN} is missing: run \`npm run build --workspace @typedstandards/cli\` first`);
  const r = spawnSync(process.execPath, [BIN, ...args], { env: { ...options.env }, input: Buffer.from(options.stdin ?? ''), encoding: 'buffer' });
  const out = r.stdout.toString('utf8');
  return {
    code: r.status,
    stdout: r.stdout,
    stderr: r.stderr,
    out,
    err: r.stderr.toString('utf8'),
    json: () => JSON.parse(out) as Record<string, unknown>,
  };
}

/** A scratch directory, removed by the returned function. */
export function scratch(): { dir: string; write(name: string, content: string | Uint8Array): string; cleanup(): void } {
  const dir = mkdtempSync(join(tmpdir(), 'typedstandards-cli-'));
  return {
    dir,
    write: (name, content) => {
      const path = join(dir, name);
      writeFileSync(path, content);
      return path;
    },
    cleanup: () => rmSync(dir, { recursive: true, force: true }),
  };
}

/** An in-memory `Io` for in-process runs: files by path, captured output. */
export function memoryIo(
  files: Record<string, string | Uint8Array> = {},
  env: Record<string, string> = {},
  overrides: Partial<Io> = {},
): Io & { out: string[]; err: string[] } {
  const out: string[] = [];
  const err: string[] = [];
  return {
    env,
    readFile: (path) => {
      const f = files[path];
      if (f === undefined) throw new Error(`ENOENT: no such file, open '${path}'`);
      return typeof f === 'string' ? new TextEncoder().encode(f) : f;
    },
    stdout: (t) => void out.push(t),
    stderr: (t) => void err.push(t),
    parseArgs: parseArgs as ParseArgs,
    now: () => new Date('2026-09-26T12:00:00.000Z'),
    uuid: () => '0a1b2c3d-4e5f-4a6b-8c7d-9e0f1a2b3c4d',
    version: '0.0.0-test',
    out,
    err,
    ...overrides,
  };
}

/** A minimal v0.1 envelope input under a self-certifying signer, for a file signed with --output-file. */
export function fileInput(extra: Record<string, unknown> = {}): Record<string, unknown> {
  return {
    type: 'content/analysis/v1',
    producerProfile: 'scripted-recomputation/example',
    captureMethod: 'script-run',
    prompt: 'Sign the file as the output of a scripted run.',
    promptVisibility: 'full_text',
    queries: [],
    dataSources: [],
    cost: { model: 'none' },
    skillMetadata: {},
    trace: {},
    signer: { bindingTier: 'pseudonymous', displayName: 'Example signer' },
    ...extra,
  };
}
